ExtraHour/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from accounts.views import home
urlpatterns = [
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    #path('api/', include(('api.urls', 'accounts'), namespace='api')),
    path('freelancer/', include(('freelancer.urls',
                                 'freelancer'), namespace='freelancer')),
    path('client/', include(('client.urls', 'client'), namespace='client')),
    path('job/', include(('job.urls', 'job'), namespace='job')),
    path('purposal_contract/', include(('purposal_contract.urls',
                                        'purposal_contract'), namespace='purposal_contract')),
    path('skill_test/', include(('skill_test.urls', 'skill_test'), namespace='skill_test')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('admin/', admin.site.urls),
    path('',home, name= 'home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from . import views
urlpatterns = [
    path('login' ,  views.Login , name= 'login'),
    path('about_us' ,  views.about_us , name= 'about_us'),
    path('contact' ,  views.contact , name= 'contact'),
    path('blog' ,  views.blog , name= 'blog'),
    path('logout' ,  views.Logout , name= 'logout'),
    path('signup', views.signup, name ='signup'),
    path('',views.home, name= 'home'),
    path('reset_done',views.reset_done, name= 'reset_done'),
    path('check_username_exist',views.check_username_exist, name= 'check_username_exist'), 
    
    url(r'^reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.reset_confirm, name='reset_confirm'),
    path('reset_form',views.reset_form, name= 'reset_form'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),

       # rl(r'^login/$', auth_views.login, {'template_name': 'core/login.html'}, name='login')
    
]

blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from . import views
urlpatterns = [
    path('post_blog/' ,  views.post_blog , name= 'post_blog'),
    path('' ,  views.blog , name= 'blog'),
     path('post_comment' ,  views.post_comment , name= 'post_comment'),
    path('blog_single/' ,  views.blog_single , name= 'blog_single'),
       url(r'^blog_single/(?P<id>\d+)/$',
        views.blog_single, name='blog_single'),
    

]

client/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from . import views
urlpatterns = [
 path('signup_company/', views.signup_company , name = "signup_company"),
  path('signup_client/', views.signup_client , name = "signup_client"),
  url(r'^purposal_list/(?P<job_id>\d+)/$',
        views.purposal_list, name='purposal_list'),
  url(r'^purposal_single/(?P<purposal_id>\d+)/$',
        views.purposal_single, name='purposal_single'),
  url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
]

freelancer/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('signup/', views.signup_freelancer, name='signup_freelancer'),
   path('test/', views.test, name='test'),
   path('portfolio/', views.portfolio_save, name='portfolio_save'),

       # rl(r'^login/$', auth_views.login, {'template_name': 'core/login.html'}, name='login')
    
]

job/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

urlpatterns = [
   path('post_job/', views.post_job, name='post_job'),
   url(r'^job_single/(?P<job_id>\d+)/$',
        views.job_single, name='job_single'),
   path('job_search/', views.job_search, name='job_search'),
     path('job_listing/', views.job_listing, name='job_listing'),
       # rl(r'^login/$', auth_views.login, {'template_name': 'core/login.html'}, name='login')
    
]

purposal_contract/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

urlpatterns = [
   url(r'^purposal/(?P<job_id>\d+)/$',
        views.purposal, name='purposal'),
        url(r'^message_listing/$',
        views.message_listing, name='message_listing'),
        url(r'^contract/(?P<purposal_id>\d+)/(?P<freelancer_id>\d+)/$',
        views.contract, name='contract'),
        url(r'^client/$',  views.client, name='client'),
        url(r'^activate/(?P<purposal_id>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
      #   url(r'^message/(?P<client_id>\d+)/(?P<freelancer_id>\d+)/(?P<purposal_id>\d+)/$',
      #   views.message, name='message'),

       # rl(r'^login/$', auth_views.login, {'template_name': 'core/login.html'}, name='login')
    
]

skill_test/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

urlpatterns = [
         url(r'^(?P<quiz_id>\d+)/$',
        views.quiz_taker, name='quiz_taker'),
        path('quizes/', views.quizes ,name='quizes'),

        path('user_ans', views.user_ans ,name='user_ans'),
        url(r'^result/(?P<quiz_taker_id>\d+)/$',
        views.result, name='result'),


       # rl(r'^login/$', auth_views.login, {'template_name': 'core/login.html'}, name='login')
    
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Catagory(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("Catagory_detail", kwargs={"pk": self.pk})


class Tag(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    def __str__(self):
        return self.title

class Post(models.Model):
    user = models.ForeignKey(User,  on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    summary = models.TextField()
    published = models.BooleanField(default = False)
    created_at =  models.DateTimeField( auto_now_add=True)
    updated_at =  models.DateTimeField(auto_now_add=False , null =True,blank= True)
    published_at =  models.DateTimeField( auto_now_add=False, null =True,blank= True)
    content = models.TextField()
    pic = models.ImageField(default = 'apps.png')
    catagory = models.ManyToManyField(Catagory)
    tag = models.ManyToManyField(Tag)
    

    def __str__(self):
        return self.title



class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    title = models.CharField( max_length=255)
    published = models.BooleanField(default = False)
    created_at =  models.DateTimeField( auto_now_add=True)
    published_at =  models.DateTimeField( auto_now_add=False , null =True,blank= True)
    content = models.TextField()


    def __str__(self):
        return self.title

class Comment_reply(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    title = models.CharField( max_length=255)
    published = models.BooleanField(default = False)
    created_at =  models.DateTimeField( auto_now_add=True)
    published_at =  models.DateTimeField( auto_now_add=False)
    content = models.TextField()

    def __str__(self):
        return self.title

skill_test/models.py
from freelancer import models as f_model
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
class Quiz(models.Model):
    name = models.CharField(max_length=1000)
    questions_count = models.IntegerField(default=0)
    description = models.CharField(max_length=70)
    created = models.DateTimeField(auto_now_add=True)
    #roll_out = models.BooleanField(default=False)
    class Meta:
        ordering = ['created',]
        verbose_name_plural ='Quizzes'
    def __str__(self):
        return self.name
class Choice(models.Model):
    choice1 = models.CharField(max_length = 255)
    choice2 = models.CharField(max_length = 255)
    choice3 = models.CharField(max_length = 255)



class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    label = models.CharField(max_length=1000)
    order = models.IntegerField(default=0)
    choice =  models.OneToOneField(Choice, on_delete=models.CASCADE)
    answer = models.CharField(max_length=1000)
    def __str__(self):
        return self.label



class QuizTakers(models.Model):
    freelancer = models.ForeignKey(f_model.Freelancer, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    correct_answers = models.IntegerField(default=0)
    completed = models.BooleanField(default=False)
    start_time = models.DateTimeField(auto_now_add=True)
    end_time = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.freelancer.user.username

class user_answer(models.Model):
    quizTakers = models.ForeignKey(QuizTakers,on_delete=models.CASCADE)
    question = models.OneToOneField(Question, on_delete=models.SET_NULL,null=True)
    choice = models.CharField(max_length = 10)
    is_correct = models.BooleanField(default=False)
    def __str__(self):
        return self.choice

@receiver(post_save, sender=Quiz)
def set_default_quiz(sender, instance, created,**kwargs):
    quiz = Quiz.objects.filter(id = instance.id)
    quiz.update(questions_count=instance.question_set.filter(quiz=instance.pk).count())
@receiver(post_save, sender=Question)
def set_default(sender, instance, created,**kwargs):
    quiz = Quiz.objects.filter(id = instance.quiz.id)
    quiz.update(questions_count=instance.quiz.question_set.filter(quiz=instance.quiz.pk).count())

blog/views.py
from django.shortcuts import render
from .models import *
from datetime import datetime
from django.http import HttpResponse , JsonResponse
import json
from django.views.decorators.csrf import csrf_exempt

def post_blog(request):
    if request.method == 'GET':
        catagory = Catagory.objects.all()
        tag = Tag.objects.all()
        print(catagory)
        return render(request, 'post_blog.html',{'tag':tag , 'catagory' : catagory})
    else:
        user = request.user
        title = request.POST['title']
        pic = request.FILES['pic']
        summary = request.POST['summary']
        content = request.POST['content']
        published = True
        tags = request.POST.getlist('tag')
        print(tags)
        catagorys = request.POST.getlist('catagory')
        
        post = Post(user=user,title=title,pic=pic,summary=summary,content=content,published=published,published_at=datetime.now())
        post.save()
        if len(tags) > 0:
            for tag in tags:
                tagg = Tag.objects.filter(title = tag).first()
                post.tag.add(tagg)
            post.save()
        if len(catagorys) > 0:
            for cat in catagorys:
                catagory = Catagory.objects.filter(title = cat).first()
                post.catagory.add(catagory)
            post.save()
        
def blog(request):
    blog = Post.objects.all()
    return render(request,'blog.html',{'blogs':blog})

def blog_single(request,id):
    blog = Post.objects.get(id = id )
    return render(request,'blog-single.html',{'blog':blog})
def publish_dashboard(request):
    pass


@csrf_exempt
def post_comment(request):
    print('sdjgksjafkjsfahasfhk')
    pos = request.POST.get('post_id')
    print(pos)
 
    post = Post.objects.get(pk = int(pos))
    message = request.POST.get('message')
    print(message)
    # content = request.POST['content']
    Comment(post = post , title ='shajkdfhsjkl' , content = message).save()
    return render(request,'blog.html',{'blogs':blog})
def publish_comment(request,id):
    comment = Comment.objects.get(id = id)
    comment.published = True
    comment.save()

@csrf_exempt
def comment_reply(request , id):
    pos = int(request.POST['comment_id'])
    comment = Comment.objects.get(id = pos)
    title = request.POST['title']
    content = request.POST['content']
    Comment(comment = comment , title =title , content = content).save()


def publish_comment_reply(request,id):
    comment = Comment_reply.objects.get(id = id)
    comment.published = True
    comment.save()
# Create your views here.

skill_test/views.py
from django.shortcuts import render
from skill_test.models import *
from django.forms.models import model_to_dict
from django.http import HttpResponse , JsonResponse
from django.core import serializers
import json
from datetime import datetime ,timedelta
from freelancer import models as f_model
from django.views.decorators.csrf import csrf_exempt


def quizes(request):
    quizes = Quiz.objects.all()
    return render(request,'test.html',{'quizes':quizes})


def quiz_taker(request,quiz_id):
    freelancer = f_model.Freelancer.objects.get(user = request.user)
    end_time = datetime.now() + timedelta( minutes = 15)
    quiz = Quiz.objects.get(pk = quiz_id)
    QuizTakers(quiz=quiz,end_time=end_time,freelancer=freelancer).save()
    questions = Question.objects.filter(quiz = quiz).first()
    return render(request,'skill_test.html',{'question':questions})



@csrf_exempt
def user_ans(request):
    # return render(request,'contact.html')#,{'quiz_taker':quiz_taker})
    user_answer = request.POST.get('user_answer')
    question_id = request.POST.get('question_id')
    q_no = int(request.POST.get('q_no'))
    print(question_id)
    print(user_answer)
    
    question1 = Question.objects.get(pk = question_id)
    question = Question.objects.get(pk = (int(question_id)+1))
    freelancer = f_model.Freelancer.objects.get(user= request.user)
    quiz_taker = QuizTakers.objects.filter(freelancer = freelancer)
    quiz_taker = quiz_taker.last() 
    
 


    if user_answer == question1.answer:
        quiz_taker.correct_answers = 1 + quiz_taker.correct_answers
        quiz_taker.save()
    # if q_no == 6 :
    #     return render(request,'quiz_result.html',{'quiz_taker':quiz_taker})
    # q_no = q_no + 1
    # if q_no == quiz_taker.quiz.questions_count:
    #    # question = t_model.Question.objects.all().first()
    #     freelancer = f_model.Freelancer.objects.get(user = request.user)
    #     quiz_taker = QuizTakers.objects.filter(freelancer=freelancer)
    #     quiz_taker = quiz_taker.last()
    # job=j_model.Job.objects.all()
        # return render(request,'contact.html',{'question': question , 'quiz_taker':quiz_taker})
    
    # count = quiz_taker.quiz.questions_count
    count = Question.objects.filter(quiz = quiz_taker.quiz ).last()
    sawal = {'question':question.label,
    'id':int(question_id)+1,
    'choice1':question.choice.choice1,
    'choice2':question.choice.choice2,
    'choice3':question.choice.choice3,
    'q_no':q_no,
    'count':count.id,
    'quiz_taker_id':quiz_taker.id
    } 
    print(type(sawal))
    return HttpResponse(json.dumps(sawal),content_type='text/json-comment-string') 




def result(request , quiz_taker_id):
    quiz_taker = QuizTakers.objects.get( pk = int(quiz_taker_id))
    return render(request,'result.html',{'quiz_taker':quiz_taker}) 

ExtraHour/templates/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}/{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

ExtraHour/templates/login.html
{%load static%}
<!Doctype html>
<html lang="en">

<head>
    <title>ExtraHour:Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <link rel="stylesheet" href="{% static 'css/custom-bs.css'%}">
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.cs'%}s">
    <link rel="stylesheet" href="{% static 'css/bootstrap-select.min.css'%}">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css'%}">
    <link rel="stylesheet" href="{% static 'fonts/line-icons/style.css'%}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/quill.snow.css'%}">
    <link rel="stylesheet" href="{% static 'css/fontawsome.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/all.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/all.css'%}">



    <!-- MAIN CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css'%}">


    <style>
        .container i {
            float: right;
            margin-top: -25px;
            padding-right: 8px;
        }

        .container form {
            margin-left: 30%;
            margin-bottom: 10%;
        }

        @media screen and (min-width:414px) {
            .container i {
                float: right;
                margin-top: -8%;
                padding-right: 8px;
            }
        }

        @media screen and (min-width:800px) {
            .container i {
                float: right;
                margin-top: -5%;
                padding-right: 8px;
            }
        }

        @media screen and (min-width:375px) {
            .container i {
                float: right;
                margin-top: -4%;
                padding-right: 8px;
            }
        }

        @media screen and (min-width:1024px) {
            .container i {
                float: right;
                margin-top: -7%;
                padding-right: 8px;
            }
        }

        @media screen and (min-width:320px) {
            .container i {
                float: right;
                margin-top: -25px;
                padding-right: 8px;
            }
        }

        @media screen and (min-width:316px) {
            .container i {
                float: right;
                margin-top: -30px;
                padding-right: 8px;
            }
        }

        .mb-4 {
            margin-left: 29% !important;
        }

        h2 {
            margin-left: 29% !important;
        }

        @media screen and (max-width: 361px) {
            .container form {
                margin-left: 0;
                margin-bottom: 0;
            }
        }

        @media screen and (max-width: 361px) {
            .mb-4 {
                margin-left: 0 !important;
            }
        }

        @media screen and (max-width: 361px) {
            h2 {
                margin-left: 0 !important;
            }
        }
    </style>
</head>

<body id="top">

    <div id="overlayer"></div>
    <div class="loader">
        <div class="spinner-border text-primary" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>


    <div class="site-wrap">

        <div class="site-mobile-menu site-navbar-target">
            <div class="site-mobile-menu-header">
                <div class="site-mobile-menu-close mt-3">
                    <span class="icon-close2 js-menu-toggle"></span>
                </div>
            </div>
            <div class="site-mobile-menu-body"></div>
        </div>
        <!-- .site-mobile-menu -->


        <!-- NAVBAR -->
        <header class="site-navbar mt-3">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="site-logo col-6"><a href="{% url 'accounts:home' %}">ExtraHour</a></div>

                    <nav class="mx-auto site-navigation">
                        <ul class="site-menu js-clone-nav d-none d-xl-block ml-0 pl-0">
                            <li><a href="{% url 'accounts:home' %}" class="nav-link">Home</a></li>
                            <li><a href="{% url 'accounts:about_us' %}">About</a></li>
                            <li class="has-children">
                                <a href="{% url 'job:job_listing' %}">Job Listings</a>
                                <ul class="dropdown">
                                    <li><a href="{% url 'job:job_single' %}">Job Single</a></li>
                                </ul>
                            </li>
                            <li class="has-children">
                                <a href="{% url 'accounts:blog' %}">Blog</a>
                                <ul class="dropdown">
                                    <li><a href="{% url 'blog:blog_single' %}">Blog Single</a></li>

                                </ul>
                            </li>

                            <li><a href="{% url 'accounts:contact' %}">Contact</a></li>
                            <li class="d-lg-none"><a href="{% url 'job:post_job' %}"><span class="mr-2">+</span> Post a
                                    Job</a>
                            </li>
                            <li class="d-lg-none"><a href="{% url 'accounts:login' %}">Login</a></li>
                        </ul>
                    </nav>

                    <div class="right-cta-menu text-right d-flex aligin-items-center col-6">
                        <div class="ml-auto">
                            <a href="{% url 'job:post_job' %}"
                                class="btn btn-outline-white border-width-2 d-none d-lg-inline-block"><span
                                    class="mr-2 icon-add"></span>Post a Job</a>
                            {% if user.is_authenticated %}
                            <a href="{% url 'accounts:logout' %}"
                                class="btn btn-primary border-width-2 d-none d-lg-inline-block"><span
                                    class="mr-2 icon-lock_outline"></span>Log Out</a>
                            {% else %}
                            <a href="{% url 'accounts:login' %}"
                                class="btn btn-primary border-width-2 d-none d-lg-inline-block"><span
                                    class="mr-2 icon-lock_outline"></span>Log In</a>
                            {% endif %}
                        </div>
                        <a href="#" class="site-menu-toggle js-menu-toggle d-inline-block d-xl-none mt-lg-2 ml-3"><span
                                class="icon-menu h3 m-0 p-0 mt-2"></span></a>
                    </div>

                </div>
            </div>
        </header>

        <!-- HOME -->
        <section class="section-hero overlay inner-page bg-image"
            style="background-image: url(https://source.unsplash.com/1600x900/?computing);" id="home-section">
            <div class="container">
                <div class="row">
                    <div class="col-md-7">
                        <h1 class="text-white font-weight-bold">Login</h1>
                        <div class="custom-breadcrumbs">
                            <a href="{% url 'accounts:home' %}">Home</a> <span class="mx-2 slash">/</span>
                            <span class="text-white"><strong>Login</strong></span>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class="site-section">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 mb-5">
                        <h2 class="mb-4">Log In To Extra Hour</h2>
                        <form action="login" method="POST" class="p-4 border rounded">
                            {% csrf_token %}
                            <div class="row form-group">
                                <div class="col-md-12 mb-3 mb-md-0">
                                    <label class="text-black" for="fname">Username</label>
                                    <input type="text" name="email" class="form-control" placeholder="Username"
                                        required>
                                </div>
                            </div>
                            <div class="row form-group ">
                                <div class="col-md-12 mb-3 mb-md-0">
                                    <label class="text-black" for="fname">Password</label>
                                    <input type="password" name="password" id="password" class="form-control"
                                        placeholder="Password" required>
                                    <i class="fa fa-eye" id="togglePassword" aria-hidden="true"></i>
                                </div>
                            </div>

                            <div class="row form-group">
                                <div class="col-md-12 mb-3 mb-md-0">
                                    <input type="submit" value="Log In" class="btn px-4 btn-primary text-white">
                                    <div><a href={% url 'accounts:reset_form' %}>Forget password</a></div>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </section>

        <footer class="site-footer">

            <a href="#top" class="smoothscroll scroll-top">
                <span class="icon-keyboard_arrow_up"></span>
            </a>

            <div class="container">
                <div class="row mb-5">
                    
                    <div class="col-6 col-md-3 mb-4 mb-md-0">
                        <h3>Company</h3>
                        <ul class="list-unstyled">
                            <li><a href="{% url 'accounts:about_us' %}">About Us</a></li>
                        </ul>
                    </div>
                    
                    <div class="col-6 col-md-3 mb-4 mb-md-0">
                        <h3>Contact Us</h3>
                        <div class="footer-social">
                            <a href="https://www.facebook.com/"><span class="icon-facebook"></span></a>
                            <a href="#"><span class="icon-instagram"></span></a>
                            <a href="#"><span class="icon-linkedin"></span></a>
                        </div>
                    </div>
                </div>

            </div>
        </footer>

    </div>

    <!-- SCRIPTS -->
    <script src="{% static 'js/jquery.min.js'%}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js'%}"></script>
    <script src="{% static 'js/isotope.pkgd.min.js'%}"></script>
    <script src="{% static 'js/stickyfill.min.js'%}"></script>
    <script src="{% static 'js/jquery.fancybox.min.js'%}"></script>
    <script src="{% static 'js/jquery.easing.1.3.js'%}"></script>


    <script src="{% static 'js/jquery.waypoints.min.js'%}"></script>
    <script src="{% static 'js/jquery.animateNumber.min.js'%}"></script>
    <script src="{% static 'js/owl.carousel.min.js'%}"></script>
    <script src="{% static 'js/quill.min.js'%}"></script>


    <script src="{% static 'js/bootstrap-select.min.js'%}"></script>

    <script src="{% static 'js/custom.js'%}"></script>
    <script src="{% static 'js/app.js'%}"></script>



</body>

</html>